plugins {
    id "com.android.application"
}

android {
    namespace "com.ztqc.smsrelay"
    compileSdk 35

    defaultConfig {
        applicationId "com.ztqc.smsrelay"
        minSdk 23
        targetSdk 35
        versionCode 33
        versionName "0.3.15"
    }
}

dependencies {
    implementation "com.squareup.okhttp3:okhttp:4.12.0"
}
