"""add user workflow access

Revision ID: 6ac6769ce0b2
Revises: 004
Create Date: 2026-04-27 23:24:54.205814
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac6769ce0b2'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_workflow_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['dify_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'workflow_id')
    )
    with op.batch_alter_table('dify_tasks') as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('ix_dify_tasks_status')
        batch_op.create_index('ix_dify_tasks_id', ['id'], unique=False)
        batch_op.create_index('ix_dify_tasks_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('dify_workflows') as batch_op:
        batch_op.create_index('ix_dify_workflows_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_dify_workflows_id', ['id'], unique=False)

    with op.batch_alter_table('materials') as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index('ix_materials_category', ['category'], unique=False)
        batch_op.create_index('ix_materials_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_materials_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_materials_id', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Batch mode keeps this historical downgrade valid on SQLite while
    # preserving the same schema transition on PostgreSQL.
    with op.batch_alter_table('materials') as batch_op:
        batch_op.drop_index(op.f('ix_materials_id'))
        batch_op.drop_index(op.f('ix_materials_deleted_at'))
        batch_op.drop_index(op.f('ix_materials_created_by'))
        batch_op.drop_index(op.f('ix_materials_category'))
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   autoincrement=True)

    with op.batch_alter_table('dify_workflows') as batch_op:
        batch_op.drop_index(op.f('ix_dify_workflows_id'))
        batch_op.drop_index(op.f('ix_dify_workflows_created_by'))

    with op.batch_alter_table('dify_tasks') as batch_op:
        batch_op.drop_index(op.f('ix_dify_tasks_user_id'))
        batch_op.drop_index(op.f('ix_dify_tasks_id'))
        batch_op.create_index(op.f('ix_dify_tasks_status'), ['status'], unique=False)
        batch_op.alter_column('progress',
                   existing_type=sa.String(length=255),
                   type_=sa.TEXT(),
                   existing_nullable=True)
        batch_op.alter_column('task_id',
                   existing_type=sa.String(length=100),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    op.drop_table('user_workflow_access')
    # ### end Alembic commands ###
