"""add xhs tables

Revision ID: 99f6d1f104b3
Revises: 007
Create Date: 2026-04-30 16:42:23.327593
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f6d1f104b3'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xhs_environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.String(length=100), nullable=False, comment='云登环境ID'),
    sa.Column('account_name', sa.String(length=200), nullable=False, comment='云登账号名称'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('proxy_info', sa.String(length=500), nullable=True, comment='代理信息'),
    sa.Column('group_name', sa.String(length=200), nullable=True, comment='分组名称'),
    sa.Column('labels', sa.String(length=500), nullable=True, comment='标签(逗号分隔)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active/inactive'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xhs_environments_id'), 'xhs_environments', ['id'], unique=False)
    op.create_index(op.f('ix_xhs_environments_shop_id'), 'xhs_environments', ['shop_id'], unique=True)
    op.create_table('xhs_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='发布人ID'),
    sa.Column('environment_id', sa.Integer(), nullable=False, comment='云登环境ID'),
    sa.Column('feed_id', sa.String(length=100), nullable=True, comment='小红书帖子ID'),
    sa.Column('xsec_token', sa.String(length=200), nullable=True, comment='小红书安全令牌'),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_urls', sa.JSON(), nullable=True, comment='图片路径列表'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='publishing/success/failed/deleted'),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('collect_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='最后数据同步时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xhs_posts_environment_id'), 'xhs_posts', ['environment_id'], unique=False)
    op.create_index(op.f('ix_xhs_posts_id'), 'xhs_posts', ['id'], unique=False)
    op.create_index(op.f('ix_xhs_posts_user_id'), 'xhs_posts', ['user_id'], unique=False)
    op.create_table('user_xhs_environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['xhs_environments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'environment_id', name='uq_user_env')
    )
    op.create_index(op.f('ix_user_xhs_environments_environment_id'), 'user_xhs_environments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_user_xhs_environments_id'), 'user_xhs_environments', ['id'], unique=False)
    op.create_index(op.f('ix_user_xhs_environments_user_id'), 'user_xhs_environments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_xhs_environments_user_id'), table_name='user_xhs_environments')
    op.drop_index(op.f('ix_user_xhs_environments_id'), table_name='user_xhs_environments')
    op.drop_index(op.f('ix_user_xhs_environments_environment_id'), table_name='user_xhs_environments')
    op.drop_table('user_xhs_environments')
    op.drop_index(op.f('ix_xhs_posts_user_id'), table_name='xhs_posts')
    op.drop_index(op.f('ix_xhs_posts_id'), table_name='xhs_posts')
    op.drop_index(op.f('ix_xhs_posts_environment_id'), table_name='xhs_posts')
    op.drop_table('xhs_posts')
    op.drop_index(op.f('ix_xhs_environments_shop_id'), table_name='xhs_environments')
    op.drop_index(op.f('ix_xhs_environments_id'), table_name='xhs_environments')
    op.drop_table('xhs_environments')
    # ### end Alembic commands ###
